site_name: TriBench
site_description: A Reproducible and Extensible Benchmark Suite for Triton Kernels.
site_author: TriBench Team
repo_url: https://github.com/H1yori233/TriBench
repo_name: H1yori233/TriBench

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Commands: commands.md
  - Slides: slides.md
